algoritmo "RELATIONSHIP"
// Função :  pedido de namoro
// Autor :
// Data : 11:11 11/11
// Seção de Declarações: EU TE AMO
var
       amor: caracter
inicio
// Seção de Comandos
   repita
   escreval ("aceita namorar comigo? (sim/nao)")
     leia (amor)
     escolha (amor)
     caso "sim"
             escreval ("<3")
     outrocaso
            escreval ("ctz?? e aí qual vai ser")
     fimescolha
     ate (amor="sim")
fimalgoritmo
